layout_spectrum: 1
color:
  saturation: 0.7824752
  lightness: 0.7408201
  brandStrength: 0.09246113
  rhythmicContrast: 0.3804253
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.1990627
name: Tesla Tuners
